### ISSUE TITLE
[Feature Request] Custom config file name

### ISSUE THREAD

**Issue by y-lohse** [CPatchane/create-cozy-app#1003]
As far as I know, cozy-scripts will automatically load `app.config.js` and nothing else. In drive, we would benefit of having multiple configuration files that we could load via a command line argument.

[Here is our config file](https://github.com/cozy/cozy-drive/blob/master/app.config.js#L13) — the problem mostly comes from the fact that we have 2 apps in the same repo.

This isn't urgently needed at all, just a nice to have to be considered.

**Comment by CPatchane** [comment]
Thanks @y-lohse for this issue, I added a new option for that in the #1058 PR :)
