### ISSUE TITLE
dev (watch) Target browser public page, no asset

### ISSUE THREAD

**Issue by Crash--** [CPatchane/create-cozy-app#1041]
When we run the app in dev mode, the public page is not working since we can't access to cozybar, cozyclient and so on.

Building the app fix the issue...

We think this is related to : https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/config/webpack.environment.dev.js#L32-L36 

We should copy these files in the `public` directory, no?

**Comment by CPatchane** [comment]
Thanks @Crash-- for this issue 👍 
Fixed by #1042
