### ISSUE TITLE
Transpiled styles from cozy-ui are not included in production build

### ISSUE THREAD

**Issue by y-lohse** [CPatchane/create-cozy-app#1198]
Related to https://github.com/cozy/cozy-drive/pull/1620

When using the transpiled version of cozy-ui, we need to include the associated stylesheet. The recommended way to do this is `import 'cozy-ui/react/stylesheet.css'`.

However when doing this, the file is not included in production builds (but works fine in dev), presumably because it gets tree-shaken.

**Comment by Crash--** [comment]
Link from @ptbrowne https://github.com/webpack/webpack/issues/6741#issuecomment-372720641
