### ISSUE TITLE
Using `bail: true` makes watch process terminate

### ISSUE THREAD

**Issue by ptbrowne** [CPatchane/create-cozy-app#130]
> bail
Report the first error as a hard error instead of tolerating it.

Using `bail: true` closes the watch process if there is an error. I would expect a watcher to continue watching if there is a problem otherwise it is very inconvenient if you are trying to remove several errors and have to restart the watcher every time.

I would use `bail: false` in `cozy-scripts/scripts/watch.js`

**Comment by CPatchane** [comment]
Will be done in #137

**Comment by CPatchane** [comment]
#137 merged
