### ISSUE TITLE
Eslint improvements

### ISSUE THREAD

**Issue by ptbrowne** [CPatchane/create-cozy-app#161]
Two small improvemements that would make the linting experience more pleasant IMHO.

- Do not output errors but warnings for syntaxic errors, as they prevent hot reloading
- Autofix syntax errors via eslint-loader

What do you think ?

I am open to do the PR ;)

**Comment by CPatchane** [comment]
Thanks @ptbrowne, it seems legit to me, feel free to open a PR :)
