### ISSUE TITLE
Missing .transifexrc file

### ISSUE THREAD

**Issue by y-lohse** [CPatchane/create-cozy-app#200]
The default `travis.yml` is failing because it references a [file that does not exist](https://github.com/CPatchane/create-cozy-app/blob/af496c3e54e3a17c748f671a58549d66f774bb8a/packages/cozy-scripts/template/app/.travis.yml#L27).
[Here's how it was fixed in collect](https://github.com/cozy/cozy-collect/blob/master/.travis.yml#L33), and that's what I'm doing in contacts too.

**Comment by CPatchane** [comment]
See #202

**Comment by CPatchane** [comment]
PR merged. Thanks @y-lohse 👍
