### ISSUE TITLE
Doc is missing for services webpack config

### ISSUE THREAD

**Issue by enguerran** [CPatchane/create-cozy-app#221]
Nothing under https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/docs/webpack-configs.md#webpackconfigservicesjs but listed in summary.

**Comment by enguerran** [comment]
In fact, I was looking for _«intents»_, and it seems I am not the only one to make a confusion between services and intents: https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/docs/webpack-configs.md#webpackconfigintentsjs

**Comment by CPatchane** [comment]
Thanks @enguerran, since services is different from intents I added the related documentation and updated the summary for the `webpack.config.intents.js` in https://github.com/CPatchane/create-cozy-app/commit/2be3cd592ecd00e6722cbeebf67e84827cca3f92.
