### ISSUE TITLE
Intents usage

### ISSUE THREAD

**Issue by enguerran** [CPatchane/create-cozy-app#222]
In https://github.com/cozy/cozy-contacts we want to use intents to let users in another application select a contact.

I try to configure the project to

- [x] build specific `html` and `js` files
- [x] load only specific `js` in specific `html` file

### build specific html and js files

I added to create `<my-project>/app.config.js` with following

```js
module.exports = [
  require('cozy-scripts/config/webpack.bundle.default.js'),
  require('cozy-scripts/config/webpack.config.intents.js')
]
```

I believe you can change your config file to include `cozy-scripts/config/webpack.config.intents.js` only if `src/targets/intents/index.html` exists using node's `path`.

Then I created following files:

```
src/targets
├── browser
│   ├── index.ejs
│   └── index.jsx
└── intents
    ├── index.ejs
    └── index.jsx
```

### load only specific js in specific html file

In `index.ejs` there is the following to include `js` files in the `html` file:

```
  <% _.forEach(htmlWebpackPlugin.files.js, function(file) { %>
      <script src="<%- file %>" defer></script>
  <% }); %>
```

but it includes every chunk. So a fix is needed.

**Comment by CPatchane** [comment]
This issue is solved by the PRs #223 and #225. You now don't need an `app.config.js` only for intents config, it will be used by default if `index.ejs` and `index.jsx/vue` are found in the folder `targets/intents`. Thanks 👍
