### ISSUE TITLE
Standard chez Cozy pour le linter et le formattage de code Javascript

### ISSUE THREAD

**Issue by kosssi** [CPatchane/create-cozy-app#312]
J'étais entrain de faire le changement des connecteurs pour mieux utiliser les standards Cozy. Mais finalement la discussion pour utiliser soit Prettier soit StandardJS n'a jamais été terminé et jamais documenté.

# Questions

- Quelle standard utilisons nous chez Cozy ? StandardJS ou Prettier.
- Quelle sont les inconvénients et les avantages des outils ?

# Situations

Les projets qui utilise StandardJS:
-
Tous avant le passage à Prettier. 
Store, Bar, Settings, Santé, Bank.

Les projets qui utilise Prettier:
-

# StandardJS

> JavaScript style guide, linter, and formatter

## Inconvénients

# Prettier

> An opinionated code formatter

## Inconvénients

# Tâche

Lister ici les différentes tâches à effectuer.

**Comment by CPatchane** [comment]
Now we use prettier (and we dropped standard) as eslint fixer in the last version of `eslint-config-cozy-app` thanks the PR #379 so it fixes this issue. Thanks a lot @kosssi and @drazik 👍
