### ISSUE TITLE
Services should not use the same babel config as the rest of the app

### ISSUE THREAD

**Issue by ptbrowne** [CPatchane/create-cozy-app#372]
## Problem

When developing on our machines, `node` is used directly on the non-bundled files. After bundling, async/await is transformed and we need regeneratorRuntime to run our files -> `babel-polyfill` is required. We should not require to do that since for services we target node 8 and async/await works by default on Node. 

## Solution

The babel configuration for services should be changed and transforms be removed. I guess the babel-preset-env could be tweaked to include just node 8.

**Comment by gregorylegarec** [comment]
Thanks @ptbrowne !

**Comment by gregorylegarec** [comment]
Actually, in some case a service may require an app library, which need to be transpiled (to handle `import` statements for example).

**Comment by ptbrowne** [comment]
Yes, this is why we keep babel but we would change the target to node.

**Comment by CPatchane** [comment]
My problem for now is that Babel Env can't handle both `node` and `browsers` targets https://github.com/babel/babel/issues/6611
I'am still thinking to find a way to split that "on demand", it would be too bad to make dedicated babel config for that :/

**Comment by CPatchane** [comment]
Is this PR #500 enough for this issue? Knowing that `json-loader` will be removed later since it's automatically handled by Webpack 4.

**Comment by CPatchane** [comment]
The version 0.7.0 of the eslint-config and babel-preset `cozy-app` are now splitted to handle "js without jsx" for the first and node for the second. I updated the PR #500, it should now fix this issue.
