### ISSUE TITLE
Feedback from using cozy-create-app for cozy-sante

### ISSUE THREAD

**Issue by ptbrowne** [CPatchane/create-cozy-app#56]
I post here my feedback concerning cozy-create-app as I integrate it with cozy-sante :)

### Customize webpack

- [x] Add "You can create app.config.js" to customize at the end of the initialization 
- [ ] If you use an `app.config.js` it is mainly to tweak some stuff, therefore I think you should not have to reimport the default bundle ? `preact-cli` solves this problem by passing the default config to your module so that you can customize it.

### Default webpack options

- [x] Modules + chunks clutter the build view

```
{
      modules: true, // display modules
      chunks: true,  // display chunks
}
```

- [x] `babel-loader` option `cache` could be set to `true`

### Babel

- [x] `transform-class-properties`

```
class {
  handleClick = () => {}
}
```

is a pattern we use across our apps that avoids binding event handler in the constructor. It needs
the following babel transform : 

```
  "plugins": [
    "transform-class-properties"
  ]
```

### Performance

*     `app1511730fbaa04962085e.bundle.js    2.22 MB       0  [emitted]  [big]  app`

Already big :/

### DX

* `yarn watch` crashes if there is an error during the first compilation

### Targets

I think we should not have an `index.jsx`/`index.ejs` per target as it will lead to files that
diverge and then it is hard to see the differences. I would put `index.ejs` and
`index.jsx` in `src/`.

### Integration with cozy-client

The store needs an instance of the client, lib/store should export a function taking the client to be able to then instantiate cozyMiddleware.

### Vendor directory in targets

I don't think it is the proper name since vendor means something that it is not from you, for example a library from another vendor.

**Comment by CPatchane** [comment]
Thanks @ptbrowne for your feedback 👍 

# Customize webpack

Completely agree about the first point but with the second point we will loose the way to be able to use the different webpack config files individually. We will have to overwrite if we want to disable something from the default configuration, it's why there is a bundle for default configuration if we just want to overwrite it (it also avoids some magical things). But it could evolve differently in the future, I save the idea in case.

# Webpack default options

It's wanted for displaying chunks and modules in development mode (only for `watch` script, it should be quieter for `build` shouldn't it?). It's useful for debugging to see how your different files are loaded through webpack loaders.
Agree about `cache` option of `babel-loader`, I'll look to enable it.

# Babel

The last version of `babel-preset-cozy-app` should use `transform-class-properties` plugin, tell me if that doesn't work correctly.

# Performance

I know -_-, I am still looking to reduce it.

# Targets

We don't need a separate `index.jsx/ejs` to handle mobile parts? If it's possible to use the same I would prefer but I didn't go so far in mobile parts/documentation for now, this part is still in progress.

# Cozy-client

I didn't integrate `cozy-client`, I would like but it's not ready yet to be used as a dependancy or provided by `cozy-stack`.

# Vendor directory in targets

Agree, these parts could change in the next days for better understanding.

**Comment by ptbrowne** [comment]
> It's wanted for displaying chunks and modules in development mode (only for watch script, it should be quieter for build shouldn't it?). It's useful for debugging to see how your different files are loaded through webpack loaders.

Maybe put it behind an environment variable like COZY_CREATE_APP_DEBUG=True or something like that ? `create-react-app` and `preact-cli` are not giving so much output and it is nicer. I wonder how much people know how to understand and debug webpack loader output.

**Comment by CPatchane** [comment]
I could add a `--debug options` to `cozy-scripts`, it could be useful for that indeed

**Comment by CPatchane** [comment]
See https://github.com/CPatchane/create-cozy-app/pull/58, https://github.com/CPatchane/create-cozy-app/pull/59 and https://github.com/CPatchane/create-cozy-app/pull/60

**Comment by ptbrowne** [comment]
Thanks, Cedric, I updated my comment to reflect that !

**Comment by CPatchane** [comment]
The main points of this issue has been handled in the last version of CCA, I suggest to close it and if we need some points again, we will open more atomic issues.
Thanks @ptbrowne 👍
