### ISSUE TITLE
Changements iphone X

### ISSUE THREAD

**Issue by y-lohse** [CPatchane/create-cozy-app#603]
On a fait quelques changements de boilerplate sur Drive pour accommoder l'écran de [l'iphone X](https://github.com/cozy/cozy-drive/pull/992/files).

Certains changements pourraient être intégrés a CCA, par exemple les changements de balise meta. Est-ce que ca t'intéresse d'avoir ca? je peux faire une PR si oui.

**Comment by CPatchane** [comment]
@y-lohse Carrément! Il y a pas mal de manques de ce côté, même les favicons n'y sont pas donc si tu as des éléments je suis preneur n'hésites pas 👍
