### ISSUE TITLE
--analyze flag could add the BundleAnalyzerPlugin

### ISSUE THREAD

**Issue by ptbrowne** [CPatchane/create-cozy-app#741]
This would facilitate debugging of the size of our bundles.

**Comment by CPatchane** [comment]
`cozy-scripts` already has an option `--analyzer` which launch `webpack-bundle-analyzer`, you can find more informations about it in the [documentation](https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/README.md#----analyzer).
Is this what you're looking for?

**Comment by ptbrowne** [comment]
Nice, thanks !
